[workspace]
members = ["as5600", "command_parser", "firmware", "hardware_abstraction", "bldc_logic"]
resolver = "3"

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"
